# Generated by Django 2.1.5 on 2019-01-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_auto_20190129_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='killboardexcelfiles',
            name='user',
        ),
        migrations.DeleteModel(
            name='KillboardExcelFiles',
        ),
    ]
