# Generated by Django 2.1.5 on 2019-01-29 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webscraper', '0004_auto_20190129_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillboardExcelFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_name', models.CharField(max_length=100)),
                ('fight_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('excel_file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
