# Generated by Django 2.1.5 on 2019-02-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0007_auto_20190201_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killboard',
            name='excel_file',
            field=models.CharField(max_length=200),
        ),
    ]
